---
# Group vars for Kubernetes control- and data-plane (worker) nodes.

ansible_user: debian

k8s_nodes_user_password_hash: >-
  {{ lookup('bitwarden.secrets.lookup',
            'e44e5c26-aa98-4298-9d27-b3e900595413') }}
k8s_nodes_version_crio: v1.33
k8s_nodes_version_kubernetes: v1.33

# This is an emergent property of the chosen dreamhost_instance_image.
k8s_nodes_volume_device: /dev/disk/by-path/virtio-pci-0000:00:05.0
k8s_nodes_volume_size: 20     # Gigabytes

k8s_nodes_vpn_ca_file: /etc/ssl/certs/internal.wust.us.pem
k8s_nodes_vpn_remote_address: >-
  {{ lookup('bitwarden.secrets.lookup',
            'b982915c-3267-4d4d-9acd-b3e90069a383') }}
