---
# Group vars for Network Attached Storage (NAS) QNAP device.

ansible_become_password: >-
  {{ lookup('bitwarden.secrets.lookup',
            'e670f7e8-27a2-4639-841c-b3ae0077a783') }}
ansible_user: mclovin
