apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f ./Documents/ejbca/bacula-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bacula-dir
  name: bacula-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bacula-dir
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f ./Documents/ejbca/bacula-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bacula-dir
    spec:
      containers:
        - image: liverwust/bacula-dir:bookworm-15.0.3-1
          name: bacula-dir
          ports:
            - containerPort: 9101
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/bacula/archive
              name: bacula-dir-claim0
            - mountPath: /opt/bacula/bsr
              name: bacula-dir-claim1
            - mountPath: /opt/bacula/log
              name: bacula-dir-cm3
            - mountPath: /opt/bacula/working
              name: bacula-dir-cm4
      restartPolicy: Always
      volumes:
        - name: bacula-dir-claim0
          persistentVolumeClaim:
            claimName: bacula-dir-claim0
        - name: bacula-dir-claim1
          persistentVolumeClaim:
            claimName: bacula-dir-claim1
        - configMap:
            name: bacula-dir-cm3
          name: bacula-dir-cm3
        - configMap:
            name: bacula-dir-cm4
          name: bacula-dir-cm4
