apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f ./Documents/ejbca/bacula-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bacula-sd
  name: bacula-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bacula-sd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f ./Documents/ejbca/bacula-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bacula-sd
    spec:
      containers:
        - image: liverwust/bacula-sd:bookworm-15.0.3-1
          name: bacula-sd
          ports:
            - containerPort: 9103
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/bacula/archive
              name: bacula-sd-claim0
            - mountPath: /opt/bacula/bsr
              name: bacula-sd-claim1
            - mountPath: /opt/bacula/etc
              name: bacula-sd-cm2
            - mountPath: /opt/bacula/log
              name: bacula-sd-claim3
            - mountPath: /opt/bacula/working
              name: bacula-sd-cm4
      restartPolicy: Always
      volumes:
        - name: bacula-sd-claim0
          persistentVolumeClaim:
            claimName: bacula-sd-claim0
        - name: bacula-sd-claim1
          persistentVolumeClaim:
            claimName: bacula-sd-claim1
        - configMap:
            name: bacula-sd-cm2
          name: bacula-sd-cm2
        - name: bacula-sd-claim3
          persistentVolumeClaim:
            claimName: bacula-sd-claim3
        - configMap:
            name: bacula-sd-cm4
          name: bacula-sd-cm4
