apiVersion: v1
binaryData:
  bacula-sd.9103.state: UW1GamRXeGhJRk4wWVhSbENnQUFBQVFBQUFBQUFBQUF3QUFBQUFBQUFBREVBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQT09
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: bacula-sd
  name: bacula-sd-cm4
