---
# Install and configure OpenVPN to connect back to my router

- name: Write out the OpenVPN client configuration
  ansible.builtin.template:
    src: etc/openvpn/client/backplane.conf.j2
    dest: /etc/openvpn/client/backplane.conf
    owner: root
    group: root
    mode: "0600"

- name: Start and enable the OpenVPN client service
  ansible.builtin.systemd_service:
    name: openvpn-client@backplane.service
    enabled: true
    state: started
    daemon_reload: true
