---

k8s_nodes_volume_key: >-
  {{ lookup('bitwarden.secrets.lookup',
            '2c41c46d-ff42-41b9-9601-b341004810c7') }}
k8s_nodes_hacluster_password_hash: >-
  {{ lookup('bitwarden.secrets.lookup',
            '73543ae0-a32f-4af7-92cd-b3450049a06a') }}
k8s_nodes_hacluster_password_plain: >-
  {{ lookup('bitwarden.secrets.lookup',
            '7a5cb334-e633-4db1-9472-b3450049bcbc') }}
