---

k8s_nodes_volume_key: >-
  {{ lookup('bitwarden.secrets.lookup',
            'e9beaf4f-8742-4625-94d1-b3410049c833') }}
k8s_nodes_hacluster_password_hash: >-
  {{ lookup('bitwarden.secrets.lookup',
            'c02aa2f1-8c00-4e71-a518-b345004a120f') }}
k8s_nodes_hacluster_password_plain: >-
  {{ lookup('bitwarden.secrets.lookup',
            '734a7bbf-dd22-4336-a324-b345004a2b62') }}
