---

k8s_nodes_volume_key: >-
  {{ lookup('bitwarden.secrets.lookup',
            'cdec8106-a73c-418c-b15c-b34100497ee7') }}
k8s_nodes_hacluster_password_hash: >-
  {{ lookup('bitwarden.secrets.lookup',
            'f5c4ec16-f46d-4247-9d5b-b3450049d5ab') }}
k8s_nodes_hacluster_password_plain: >-
  {{ lookup('bitwarden.secrets.lookup',
            'ba61ff0f-ce83-42c5-913d-b3450049f3bc') }}
